### ISSUE TITLE
Support for WAF Cloud test: add flag to override test to only look at http status code

### ISSUE THREAD

**Issue by fzipi** [fzipi/go-ftw#42]
In the process to get the status page working, we need to overwrite the test result to only check for the http status code returned.

👉 That way, we don't need to check for logs that might not be accessible in cloud vendors, or maybe the information there is partial or different.

Relying only on http status code will give us an approximate result. Results of the test should be:

- If the test has `log_contains`, and we received 403 as response, test is Passed.
- If the test has `log_contains`, and we received 200 as response, test is Failed.
- If the test has `no_log_contains`, and we received 403 as response, test is Failed.
- If the test has `no_log_contains`, and we received 200 as response, test is Passed.
- If the test has `status`, and the status in the response is in that list, test is Passed. Otherwise, test has failed.

Also, we should be able to override test `dest_addr` and `port`, as this is going to hit remote resources in most cases (a tunnel can easily be setup using `netcat`, but it is better if we just override those settings).

**Comment by airween** [comment]
Is there any way to run the test against an external host (like a WAF cloud)?

I mean the test cases contain
```
          input:
            dest_addr: "127.0.0.1"
            port: 80
            headers:
              User-Agent: "ModSecurity CRS 3 Tests"
              Host: "localhost"
```
so now I have to replace the `dest_addr`, `port` and `Host` header fields.

It would be fine to have a command line option, which helps to override these values.
