### ISSUE TITLE
Change in url.ParseQuery semantics while running 932150-2 test?

### ISSUE THREAD

**Issue by fzipi** [fzipi/go-ftw#47]
While running the latest rc, I've stumbled on this:
```
        running 932150-4: 12:18PM INF ftw/http: cannot encode data to: "932150-2=dont match commands that are not at start;tar -xzf /var/www/exfiltrate.tar.gz /etc"
12:18PM FTL ftw/http: fatal error building request: invalid semicolon separator in query
```
Looking at the test:
```
   - test_title: 932150-4
     stages:
       - stage:
           input:
             dest_addr: "127.0.0.1"
             method: "POST"
             port: 80
             headers:
               User-Agent: OWASP ModSecurity Core Rule Set
               Host: "localhost"
               Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;   q=0.5
             data: '932150-2=dont match commands that are not at start;tar -xzf /var/www/exfiltrate.tar.gz /etc'
             protocol: "http"
           output:
             no_log_contains: "id \"932150\""
```
Seems like this has changed semantics now? Need to dive a bit because previous 0.3 version (go 1.16 works).
